## Mean and variance of groups generations

In [68]:
proba_b_better_a = []
expected_loss_a = []
expected_loss_b = []

for day in range( len ( df1 ) ):


    u_a , var_a = stats.beta.stats( a = 1 + df1.loc[day, 'acc_clicks_A'], \
                                b = 1 + (df1.loc[day, 'acc_visits_A'] - df1.loc[day, 'acc_clicks_A']), moments='mv')
    u_b , var_b = stats.beta.stats( a = 1 + df1.loc[day, 'clicks_B'], \
                                b = 1 + (df1.loc[day, 'visits_B'] - df1.loc[day, 'clicks_B']), moments='mv')


    # Normal distribution Sample A and B
    x_a = np.random.normal( loc = u_a, scale = 1.25*np.sqrt( var_a ) ,size = N_mc)
    x_b = np.random.normal( loc = u_b, scale = 1.25*np.sqrt( var_b ) ,size = N_mc)


    # Norm distribution function of page A nad page B
    fa = stats.beta.pdf ( x_a, 
                         a = 1 + df1.loc[day, 'acc_clicks_A'], 
                         b = 1 + ( df1.loc[day, 'acc_visits_A'] - df1.loc[day, 'acc_clicks_A']))

    fb = stats.beta.pdf ( x_b,
                        a = 1 + df1.loc[day, 'clicks_B'],
                        b = 1 + ( df1.loc[day, 'visits_B'] - df1.loc[day, 'clicks_B'] ))
    

    # Beta distribution function of page A and B
    ga = stats.norm.pdf( x_a, loc = u_a, scale = 1.25*np.sqrt( var_a ))
    gb = stats.norm.pdf( x_b, loc = u_b, scale = 1.25*np.sqrt( var_b ))
    

    # Beta / Normal
    y = ( fa*fb ) / ( ga*gb )
    yb = y[x_b >= x_a]
    
    #Calculate probabilities
    p = ( 1/ N_mc ) * np.sum(yb)

    expected_loss_A = (1 / N_mc ) * np.sum ( ( ( x_b - x_a )*y) [x_b >= x_a] )
    expected_loss_B = (1 / N_mc ) * np.sum ( ( ( x_a - x_b )*y) [x_a >= x_b] )

    proba_b_better_a.append(p)
    expected_loss_a.append( expected_loss_A )
    expected_loss_b.append( expected_loss_B )

0.5
[0.01337951 0.8016262  0.26913064 ... 0.18641688 0.72213825 0.1840165 ]
[1. 1. 1. ... 1. 1. 1.]
[0.44533038 0.77959115 0.90095199 ... 0.75787808 0.91474028 0.75349285]
0.5
[0.66729078 0.13244493 0.40954555 ... 1.01506435 1.43686852 0.88262123]
[1. 1. 1. ... 0. 0. 1.]
[0.99292933 0.6580988  1.07138513 ... 0.39917822 0.03800325 0.63014776]
0.5
[0.50832141 0.70141582 0.77151173 ... 0.62788642 0.0911737  0.52384758]
[1. 1. 1. ... 1. 1. 1.]
[1.10528734 0.94609608 0.83301115 ... 1.0382829  0.58190835 1.10316951]
0.5
[1.25941841 0.4057633  0.51581061 ... 0.63337249 1.07531685 0.39230704]
[0. 1. 1. ... 1. 0. 1.]
[0.12072749 1.06851508 1.10452053 ... 1.03258408 0.31017198 1.05742403]
0.5
[0.39491461 0.00393279 0.17690927 ... 0.69432168 0.83550096 0.70514752]
[1. 1. 1. ... 1. 1. 1.]
[1.05967934 0.42973513 0.74046477 ... 0.95635062 0.71758591 0.9406002 ]
0.5
[0.86832107 1.03782154 0.14031719 ... 0.63473825 1.07980278 0.57859807]
[1. 0. 1. ... 1. 0. 1.]
[0.65667586 0.36408917 0.67272667 ... 1.