## Mean and variance of groups generations

In [10]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta

In [11]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta

class ThompsonAgent( object ):
    def __init__( self, prob_list ):
        self.prob_list = prob_list
    
    def pull( self, bandit_machine ):
        if np.random.random() < self.prob_list[ bandit_machine ]:
            reward = 1
        else:
            reward = 0
            
        return reward


# positive result proba    
prob_list = [ 0.25 , 0.28 ]

# experiment params
trials = 1000
episodes = 200

bandit = ThompsonAgent( prob_list )

prob_reward_array = np.zeros( len( prob_list ) )
accumulated_reward_array = []
avg_accumulated_reward_array = []


success_array = np.ones( len( prob_list ) )
failure_array = np.full( len( prob_list ), 1.0e-5 )


In [12]:
success_array

array([1., 1.])

In [17]:
failure_array

array([1.e-05, 1.e-05])

In [31]:
prob_reward = np.random.beta( success_array, failure_array )
bandit_machine = np.argmax( prob_reward )

In [32]:
bandit_machine

0

In [29]:
prob_reward

array([1., 1.])

In [2]:

import numpy as np
import pandas as pd
from flask import Flask, render_template, redirect, url_for, request



df = pd.read_csv(f"data_experiment.csv")
df['no_click'] = df['visit'] - df['click']

click_array = df.groupby( "group" ).sum().reset_index()[['click', 'no_click']]
print( click_array )

   click  no_click
0   4105      9427
1   5262      7911


In [6]:
click_array = df.groupby( "group" )[['click', 'no_click']].sum()
click_array

click  no_click
group                     
control     4105      9427
treatment   5262      7911